### ISSUE TITLE
width を実数値として解釈するか比として解釈するかはコンテナのプロパティによって決まってほしい

### ISSUE THREAD

**Issue by aoitaku** [aoitaku/quiness#1]

**Comment by aoitaku** [comment]
プロパティ名募集

**Comment by aoitaku** [comment]
width と height は別々に指定できるほうがよさそう

**Comment by uneco** [comment]
`vertical-fit` `horizontal-fit`

**Comment by uneco** [comment]
`vertical-tightly-fit` `horizontal-tightly-fit`

**Comment by uneco** [comment]
`vertical-smart-fit` `horizontal-smart-fit`

**Comment by uneco** [comment]
`width-scaling-fit` `height-scaling-fit`

**Comment by uneco** [comment]
小さければ拡大してフィット、大きければ縮小してフィットという動きなので、 `scaling`は正しいのではないかと思う

**Comment by aoitaku** [comment]
ちなみに当時は relative-width や relative-height などのプロパティが入る予定があったんですが、width や height と両立したらどうなるのかなどが不透明なのでやめました

**Comment by uneco** [comment]
`scale` | `real` のようなパラメータを渡せる何かであると考えてもいい

**Comment by aoitaku** [comment]
> `scale` | `real` のようなパラメータを渡せる何かであると考えてもいい

そのほうがよさそうな感じですね

**Comment by uneco** [comment]
`ratio` or `real` とか

**Comment by uneco** [comment]
そうなると `width-type` とか `width-arrangement` みたいなプロパティでよさそう

**Comment by aoitaku** [comment]
width-arrangement いいですね

**Comment by aoitaku** [comment]
`width-arrangement` と　`height-arrangement`  でいきます。ありがとうございました。

**Comment by uneco** [comment]
あ、でも「子の」っていうのがわかりづらい？

**Comment by uneco** [comment]
自分のぽくなってしまうような

**Comment by aoitaku** [comment]
これだと確かに自分自身ので解釈しそうな感じがある

**Comment by uneco** [comment]
flexbox だと `content` とか `item` って付いてるから子のだってわかりやすい

**Comment by uneco** [comment]
quiness 的に子のことはただ component と呼ぶ感じですかね

**Comment by aoitaku** [comment]
`horizontal-item-arrangement`, `vertical-item-arrangement` みたいな感じの

**Comment by uneco** [comment]
YES. `item` という語がほかで使われてないのが気になるけど……

**Comment by aoitaku** [comment]
item, align-items くらいでしか使ってないですね

**Comment by aoitaku** [comment]
flexbox のいうところの `justify-content` と `align-items` もなんでそうなのかよくわからない

**Comment by uneco** [comment]
align-items で使われてるなら良いとおもいます！

**Comment by uneco** [comment]
justify-content と align-items は一生覚えられないしひどい

**Comment by aoitaku** [comment]
`content` より `item` のほうが短いので `item` にします、たぶんわかるし大丈夫
